In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense,Flatten,BatchNormalization,Dropout
from keras.optimizers import Adam
from keras.regularizers import L1,L2
from keras.callbacks import EarlyStopping
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("telecom_churn.csv")

In [3]:
data.head()

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,0,128,1,1,2.7,1,265.1,110,89.0,9.87,10.0
1,0,107,1,1,3.7,1,161.6,123,82.0,9.78,13.7
2,0,137,1,0,0.0,0,243.4,114,52.0,6.06,12.2
3,0,84,0,0,0.0,2,299.4,71,57.0,3.10,6.6
4,0,75,0,0,0.0,3,166.7,113,41.0,7.42,10.1

In [4]:
data.isnull().sum()

Churn              0
AccountWeeks       0
ContractRenewal    0
DataPlan           0
DataUsage          0
CustServCalls      0
DayMins            0
DayCalls           0
MonthlyCharge      0
OverageFee         0
RoamMins           0
dtype: int64

In [5]:
data["Churn"].value_counts()

Churn
0    2850
1     483
Name: count, dtype: int64

In [6]:
x = data.drop("Churn",axis =1)

In [7]:
y = data["Churn"]

In [8]:
smote = SMOTE()

In [9]:
x,y = smote.fit_resample(x,y)

In [10]:
y.value_counts()

Churn
0    2850
1    2850
Name: count, dtype: int64

In [11]:
data.corr()*100

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
Churn,100.000000,1.654074,-25.985185,-10.214814,-8.719451,20.875000,20.515083,1.845931,7.231271,9.281243,6.823878
AccountWeeks,1.654074,100.000000,-2.473465,0.291841,1.439076,-0.379594,0.621602,3.846988,1.258067,-0.674946,0.951390
ContractRenewal,-25.985185,-2.473465,100.000000,-0.600637,-1.922291,2.452196,-4.939582,-0.375463,-4.729140,-1.910464,-4.587074
DataPlan,-10.214814,0.291841,-0.600637,100.000000,94.598173,-1.782394,-0.168407,-1.108590,73.748965,2.152556,-0.131787
DataUsage,-8.719451,1.439076,-1.922291,94.598173,100.000000,-2.172252,0.317595,-0.796208,78.166043,1.963737,16.274558
CustServCalls,20.875000,-0.379594,2.452196,-1.782394,-2.172252,100.000000,-1.342319,-1.894193,-2.801685,-1.296422,-0.963968
DayMins,20.515083,0.621602,-4.939582,-0.168407,0.317595,-1.342319,100.000000,0.675041,56.796792,0.703821,-1.015459
DayCalls,1.845931,3.846988,-0.375463,-1.108590,-0.796208,-1.894193,0.675041,100.000000,-0.796322,-2.144860,2.156479
MonthlyCharge,7.231271,1.258067,-4.729140,73.748965,78.166043,-2.801685,56.796792,-0.796322,100.000000,28.176605,11.743261
OverageFee,9.281243,-0.674946,-1.910464,2.152556,1.963737,-1.296422,0.703821,-2.144860,28.176605,100.000000,-1.102334
RoamMins,6.823878,0.951390,-4.587074,-0.131787,16.274558,-0.963968,-1.015459,2.156479,11.743261,-1.102334,100.000000

In [12]:

num_feature = ["AccountWeeks","CustServCalls", "DayMins", "DayCalls", "MonthlyCharge", "OverageFee", "RoamMins"]

In [13]:
scaler = StandardScaler()

for num in num_feature:
    x[num] = scaler.fit_transform(x[[num]])

In [14]:
x

,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,0.693916,1,1,2.700000,-0.466171,1.192136,0.462662,1.976786,-0.178472,-0.154331
1,0.154063,1,1,3.700000,-0.466171,-0.480117,1.120197,1.538392,-0.215830,1.277613
2,0.925282,1,0,0.000000,-1.173620,0.841528,0.664980,-0.340439,-1.759968,0.697095
3,-0.437204,0,0,0.000000,0.241277,1.746321,-1.509944,-0.027300,-2.988637,-1.470172
4,-0.668570,0,0,0.000000,0.948726,-0.397716,0.614400,-1.029343,-1.195444,-0.115630
...,...,...,...,...,...,...,...,...,...,...
5695,0.205478,1,0,0.000000,-0.466171,1.366305,0.968458,0.728775,1.020283,1.178027
5696,0.102649,0,0,2.753353,-0.466171,1.293148,0.614400,2.307880,0.575444,1.152728
5697,1.285183,1,0,0.000000,-0.466171,0.806560,1.170776,0.494078,1.537933,0.252734
5698,1.362305,1,0,0.000000,-0.466171,-0.527532,-0.093714,-0.501081,1.091567,-0.398284
5699,-0.231546,0,0,0.000000,1.656174,-0.616038,-0.043135,-0.938064,-0.399024,-0.702728

In [15]:

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [16]:
x_test

,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
1436,-0.462911,1,1,2.92,-0.466171,0.566859,0.816719,1.926684,0.597748,0.155278
748,0.128356,1,0,0.00,-0.466171,0.474764,0.968458,0.223210,1.332459,-0.657447
4596,0.359721,0,0,0.00,0.948726,0.956450,-1.560523,0.452051,0.919782,-0.249945
1448,0.231185,1,0,0.00,1.656174,0.826987,0.462662,-0.089928,-0.904881,-1.005757
2543,0.488258,1,1,1.86,-0.466171,0.395594,1.120197,1.388086,1.643777,-1.354068
...,...,...,...,...,...,...,...,...,...,...
219,0.128356,1,0,0.40,-1.173620,0.511925,1.019037,-0.340439,-1.988268,-1.276666
1831,-0.205839,1,1,3.05,3.778519,-0.630377,-0.548931,1.381823,1.278497,0.348784
1115,-0.077302,1,0,0.00,-0.466171,-0.425183,1.423674,-0.716205,-0.070548,0.813198
582,0.076941,1,0,0.00,-0.466171,-0.438108,0.412082,-0.966716,-1.050162,0.116577
2858,1.028111,1,1,2.00,-0.466171,1.885272,1.120197,2.289924,0.867557,-1.160562

In [37]:
model = Sequential(
    [ 
    (Dense(units =64, activation = "relu",input_shape=(x_train.shape[1],1),kernel_regularizer = L2(l2=0.01))),
    # (BatchNormalization()),
    # (Dropout(0.2)),
    (Dense(units =64//2, activation = "relu")),
    (BatchNormalization()),
    (Dense(units =16, activation = "relu")),
    (Dense(units =8, activation = "relu")),
    (Flatten()),
    (Dense(units =1, activation = "sigmoid"))
    ]
)

C:\Users\mayas\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [38]:
model.compile(optimizer = Adam(learning_rate = 0.001),loss = "binary_crossentropy",metrics = ["accuracy"])

In [39]:
x_train.shape

(4560, 10)

In [40]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                      │ (None, 10, 64)              │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 10, 32)              │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 10, 32)              │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 10, 16)              │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 10, 8)               │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 80)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 1)                   │              81 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,081 (12.04 KB)

 Trainable params: 3,017 (11.79 KB)

 Non-trainable params: 64 (256.00 B)

In [41]:
model.fit(x_train,y_train,epochs = 20,batch_size =64,validation_split = 0.2,callbacks = EarlyStopping())

Epoch 1/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.6757 - loss: 0.6561 - val_accuracy: 0.6645 - val_loss: 0.6924
Epoch 2/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7867 - loss: 0.5485 - val_accuracy: 0.7873 - val_loss: 0.6294
Epoch 3/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8279 - loss: 0.4541 - val_accuracy: 0.8246 - val_loss: 0.5576
Epoch 4/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8577 - loss: 0.4095 - val_accuracy: 0.8465 - val_loss: 0.5001
Epoch 5/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8681 - loss: 0.3897 - val_accuracy: 0.8509 - val_loss: 0.4631
Epoch 6/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8739 - loss: 0.3786 - val_accuracy: 0.8596 - val_loss: 0.4316
Epoch 7/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8772 - loss: 0.3734 - val_accuracy: 0.8586 - val_loss: 0.4209
Epoch 8/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8734 - loss: 0.3699 - val_accuracy: 0.8706 - val_loss: 0.3994
Epoch 9/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8739 - loss: 0.3674 - val_accuracy: 0.8695 - val_loss: 0.3910
Epoch 10/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8755 - loss: 0.3634 - val_accuracy: 0.8695 - val_loss: 0.3965

In [42]:
y_pred1 = model.predict(x_train)
pred_data1 =[]
for i in y_pred1:
    if i[0]>0.5:
        pred_data1.append(1)
    else:
        pred_data1.append(0)

143/143 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

In [43]:
y_pred = model.predict(x_test)
pred_data =[]
for i in y_pred:
    if i[0]>0.5:
        pred_data.append(1)
    else:
        pred_data.append(0)

36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

In [44]:
pred_data

[0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 ...]

In [45]:
accuracy_score(y_test,pred_data)*100

86.2280701754386

In [46]:
accuracy_score(y_train,pred_data1)*100

86.73245614035088

In [27]:
# from sklearn.metrics import classification_report

In [28]:
# print(classification_report(y_test, pred_data))

In [29]:
# plt.plot(model.history['loss'], label='train')
# plt.plot(model.history['val_loss'], label='val')
# plt.legend()

In [30]:
loss,accuracy = model.evaluate(x_test,y_test)

36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8807 - loss: 0.3503

In [31]:
loss

0.3502711057662964

In [32]:
accuracy

0.8807017803192139

In [33]:
model.input_shape

(None, 10, 1)

In [34]:
y_pred = model.predict(np.array([[-0.469294	,1	,1	,2.920000	,-0.477580	,0.579490	,0.833893	,1.929990	,0.587245	,0.150471]], dtype=np.float32))
pred_data =[]
for i in y_pred:
    if i[0]>0.5:
        pred_data.append(1)
    else:
        pred_data.append(0)  
pred_data

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

[0]

In [35]:
y_test

1436    0
748     0
4596    1
1448    0
2543    0
       ..
219     0
1831    0
1115    1
582     0
2858    0
Name: Churn, Length: 1140, dtype: int64

In [36]:
model.save("Ada.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.